#!/bin/bash

# config
max_usage=90
bar_width=32
# colors
white="\e[39m"
green="\e[1;32m"
red="\e[1;31m"
cyan="\e[36m"
notused="\e[35m"
dim="\e[2m"
undim="\e[0m"

# disk usage, list disks/mounts you want to check here
disks=(sda2 /mnt/nas)
printf "\n\e[36mDisk usage:\e[0m\n"

OUTPUT=$(df -h)

for disk in "${disks[@]}"; do
    line=$(echo "$OUTPUT" | grep "$disk")
    usage_percent=$(echo "$line" | awk '{print $5}')
    usage_num=$(echo $usage_percent | sed 's/%//')
    used_width=$((($usage_num*$bar_width)/100))
    # color is green if usage < max_usage, else red
    if [ "${usage_num}" -ge "${max_usage}" ]; then
        color=$red
    else
        color=$cyan
    fi
    # print green/red bar until used_width
    bar="[${color}"
    for ((i=0; i<$used_width; i++)); do
        bar+="="
    done
    # print dimmmed bar until end
    bar+="${notused}${dim}"
    for ((i=$used_width; i<$bar_width; i++)); do
        bar+="="
    done
    bar+="${undim}]"
    # print usage line & bar
    echo "${line}" | awk '{ printf("%-18s%+3s out of %+5s\n", $NF, $5, $2); }' | sed -e 's/^//'
    echo -e "${bar}" | sed -e 's/^//'
done
echo $(cat /proc/mdstat | grep 'md127')
