#!/bin/bash
export LANG='en_US.UTF-8'

declare -a containers
declare -a status

OUTPUT=$(docker ps -a --format "{{.Names}}" | awk '{print $1}')
readarray -t containers < <(xargs -n 1 printf '%s\n' <<<"$OUTPUT")

OUTPUT=$(docker ps -a --format "{{.Status}}" | awk '{print $1}')
readarray -t status < <(xargs -n 1 printf '%s\n' <<<"$OUTPUT")

# Maximum column width
#width=$((49-2))
width=$((34))

# Current line and line length
line=""
lineLen=0

echo "Docker containers:"

for i in ${!containers[@]}
do
    # Next line and next line length
    next="  ${containers[$i]}"
    nextLen=$((1+${#next}))

    # If the current line will exceed the max column with then echo the current line and start a new line
    if [[ $((lineLen+nextLen)) -gt width ]]; then
    echo -e "$line"
    lineLen=0
    line=""
    fi

    lineLen=$((lineLen+nextLen))

    # Color the next line green if it's active, else red
    if [[ "${status[$i]}" == "Up" ]]; then
    line+="\e[36m● ${containers[$i]}\e[0m "
    else
    line+="\e[1;33m▲ ${containers[$i]}\e[0m "
    fi
done

# echo what is left
echo -e "$line"
